name: Docker main

on:
  schedule:
    - cron: '15 15 * * SAT'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        proton:
          - version: GE-Proton11-1
            tags: |
              type=raw,value=proton-11
          - version: GE-Proton10-34
            tags: |
              type=raw,value=proton-10
              type=raw,value=latest
          - version: GE-Proton9-27
            tags: |
              type=raw,value=proton-9
          - version: GE-Proton8-32
            tags: |
              type=raw,value=proton-8

    name: Publishing image with ${{ matrix.proton.version }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log into registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ matrix.proton.tags }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PROTON_VERSION=${{ matrix.proton.version }}
